name: ORT Analysis

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ort:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get current repository and branch
        id: vars
        run: |
          echo "REPO_URL=https://github.com/${{ github.repository }}.git" >> $GITHUB_OUTPUT
          echo "REVISION=${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Run ORT Analysis
        uses: oss-review-toolkit/ort-ci-github-action@v1
        with:
          vcs-url: ${{ steps.vars.outputs.REPO_URL }}
          vcs-type: Git
          vcs-revision: ${{ steps.vars.outputs.REVISION }}
          ort-cli-args: 'analyze -f CycloneDX -o ort-results'

      - name: Generate HTML Report
        run: |
          java -jar ort/cli/build/libs/ort-cli-*-fat.jar report \
            -i ort-results/analyzer-result.yml \
            -f WebApp \
            -o ort-report

      - name: Upload ORT HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: ort-report
          path: ort-report/index.html
